# Generated by Django 3.0 on 2019-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sns_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snsmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snsmodel',
            name='readtext',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
