# Generated by Django 3.0 on 2019-12-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sns_app', '0002_auto_20191210_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='readtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
